# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b39738acf12bd3bbe8ed1cbd2caac2f6504af609996fbac9bb06e924a0d147d6570719bb20036d1d2da7866c56987677a891a78e55c9990c1dedac2dd1c379e

test:
  secret_key_base: 9a9f5047d34424eb2c29d47bdf027a63508a6eae4cbe8c6d46c7627ba5e3336dd521efc1c0ba8755f28cf4cc519591d23c0184111a9057ff4555c9e767950949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
